name: Notify Integration Release
on:
  push:
    paths:
      - "packs/**"
    branches:
      - main
jobs:
  determine-identifiers:
    name: Determine Identifiers
    runs-on: ubuntu-latest
    outputs:
      identifiers: ${{ steps.output-result.outputs.identifiers }}
    steps:
      - name: Checkout Nomad Pack Community Registry
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - id: determine_changed_files
        name: Determine Changed Files
        uses: jitterbit/get-changed-files@v1 # TODO: restrict to SHA
      - id: output-result
        run: |
          echo ${{ steps.determine_changed_files.outputs.all }} \
            | ./.github/scripts/files-to-identifiers.sh \
            | jq --raw-input --slurp  'split("\n") | map(select(. != ""))' \
            | jq -c .
          # echo "identifiers=world" >> "$GITHUB_OUTPUT"
