name: Notify Integration Release
on:
  push:
    paths:
      - "packs/**"
    branches:
      - main
jobs:
  sync-content:
    name: Notify Releases
    runs-on: ubuntu-latest
    steps:
      - id: determine_changed_files
        name: Determine Changed Files
        uses: jitterbit/get-changed-files@v1
      - run: |
          pwd && ls
          echo ${{ steps.determine_changed_files.outputs.all }} \
            | ./.github/scripts/files-to-identifiers.sh
